### ISSUE TITLE
Facing issue over objects when using ray multinode cluster

### ISSUE THREAD

**Issue by BalajiSelvaraj10** [Yard1/ray-skorch#17]
Ray version: 1.9.2
pandas: 1.1.5
OS: Mac

Getting below error trace when executing my code., This exception triggers from worker node.

At least one of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: cannot import name 'maybe_mangle_lambdas'
traceback: Traceback (most recent call last):
  File "/home/rayuser/.local/lib/python3.6/site-packages/ray/serialization.py", line 281, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/rayuser/.local/lib/python3.6/site-packages/ray/serialization.py", line 194, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/rayuser/.local/lib/python3.6/site-packages/ray/serialization.py", line 172, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/rayuser/.local/lib/python3.6/site-packages/ray/serialization.py", line 160, in _deserialize_pickle5_data
    obj = pickle.loads(in_band, buffers=buffers)
  File "/home/rayuser/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 118, in <module>
    from pandas.core.aggregation import reconstruct_func, relabel_result
  File "/home/rayuser/.local/lib/python3.6/site-packages/pandas/core/aggregation.py", line 25, in <module>
    import pandas.core.common as com
  File "/home/rayuser/.local/lib/python3.6/site-packages/pandas/__init__.py", line 52, in <module>
    from pandas.core.api import (
  File "/home/rayuser/.local/lib/python3.6/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "/home/rayuser/.local/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
  File "/home/rayuser/.local/lib/python3.6/site-packages/pandas/core/groupby/generic.py", line 57, in <module>
    from pandas.core.aggregation import (
ImportError: cannot import name 'maybe_mangle_lambdas' - Stack Trace - Traceback (most recent call last):

Kindly help me to resolve this asap., Pandas actually has this mentioned function(maybe_mangle_lambdas). Tried reinstalling packages.

**Comment by BalajiSelvaraj10** [comment]
Hi., Thanks for your reply.

Yes., the environment has one head node and one worker. Both have pandas 1.1.5

**Comment by Yard1** [comment]
Are you using Ray Client? (`ray.init("ray://`)

**Comment by BalajiSelvaraj10** [comment]
Implementing cluster with 2 local ubuntu machines. My code is on head node, so initiating ray using address="auto"

**Comment by Yard1** [comment]
Does this issue also happen with just one node?

**Comment by BalajiSelvaraj10** [comment]
Yes @Yard1 ., In my environment, I have one head node and one worker node. 

When I'm trying to execute my code from head node, workers are allocated from worker node too. Workers from worker node triggering these exception traces.

My code runs successfully with the help of workers from head node.

**Comment by Yard1** [comment]
Hey @BalajiSelvaraj10 would you have a time for a quick chat? We can coordinate through Ray Slack

**Comment by BalajiSelvaraj10** [comment]
Hi @Yard1 ., following is my code structure,

**xyz.py (driver)**
import logging
import pandas
import numpy
import ray
import time

my internal code snippet here. Have called a function of abc.py with remote keyword. abc.py contains only ray functions which I need to distribute among worker nodes.

**abc.py**
import ray
import logging
import pandas as pd

Please help me out to solve this. Importing pandas in both py files will cause any issue?
I’m totally new to python and ray environment. If you need any further clarifications we can do chat over slack.

**Comment by BalajiSelvaraj10** [comment]
@Yard1 

Also I'm using python3.6 which has matching pandas as maximum pandas 1.1.5.

With this relationship can we expect any issue,
python 3.6
ray 1.9.2
pandas 1.1.5
